//
//  FCPXML Media Multicam.swift
//  swift-fcpxml • https://github.com/orchetect/swift-fcpxml
//  © 2022 Steffan Andrews • Licensed under MIT License
//

#if os(macOS) // XMLNode only works on macOS

import Foundation
import SwiftTimecodeCore
import SwiftExtensions

extension FCPXML.Media.Multicam {
    /// A container of story elements organized sequentially in time.
    /// Similar to a `sequence`.
    public struct Angle: FCPXMLElement {
        public let element: XMLElement
        
        public let elementType: FCPXML.ElementType = .mcAngle
        
        public static let supportedElementTypes: Set<FCPXML.ElementType> = [.mcAngle]
        
        public init() {
            element = XMLElement(name: elementType.rawValue)
        }
        
        public init?(element: XMLElement) {
            self.element = element
            guard _isElementTypeSupported(element: element) else { return nil }
        }
    }
}

// MARK: - Parameterized init

extension FCPXML.Media.Multicam.Angle {
    public init(
        name: String? = nil,
        angleID: String
    ) {
        self.init()
        
        self.name = name
        self.angleID = angleID
    }
}

// MARK: - Structure

extension FCPXML.Media.Multicam.Angle {
    public enum Attributes: String {
        // Element-specific Attributes
        /// Angle name.
        case name
        
        /// Specifies the angle identifier.
        /// This is not the angle name, but a unique ID string randomly generated by FCP.
        case angleID
    }
    
    // contains clips
    // contains transitions
}

// MARK: - Attributes

extension FCPXML.Media.Multicam.Angle {
    /// Angle name.
    public var name: String? {
        get { element.fcpName }
        nonmutating set { element.fcpName = newValue }
    }
    
    /// Angle ID. (Required)
    public var angleID: String {
        get { element.stringValue(forAttributeNamed: Attributes.angleID.rawValue) ?? "" }
        nonmutating set { element.addAttribute(withName: Attributes.angleID.rawValue, value: newValue) }
    }
}

// MARK: - Children

extension FCPXML.Media.Multicam.Angle {
    /// Get or set story elements contained within the angle.
    public var contents: LazyCompactMapSequence<[XMLNode], XMLElement> {
        get { element.childElements }
        nonmutating set {
            element.removeAllChildren()
            element.addChildren(newValue)
        }
    }
}

// MARK: - Meta Conformances

extension FCPXML.Media.Multicam.Angle: FCPXMLElementMetaTimeline { 
    public func asAnyTimeline() -> FCPXML.AnyTimeline { .mcAngle(self) }
}

// MARK: - Typing

// Angle
extension XMLElement {
    /// FCPXML: Returns the element wrapped in an ``FCPXML/Media/Multicam/Angle`` model object.
    /// Call this on a `mc-angle` element only.
    public var fcpAsMCAngle: FCPXML.Media.Multicam.Angle? {
        .init(element: self)
    }
}

#endif
